language: python
python:
  - 3.4
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
script:
  - coverage run --source=apps manage.py test
after_success:
  - coveralls
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: CmKGBrhGhM8xq33JJsHwRgG3uA5d+WO6rZJIyFSCjAkrUB/EoEl4vz+nttuLOvxHID40Tr4CefZIMPfJIcpKJJxccSwCLj+kDpmuDMc3ld7HG2xRnODKIDeCaV2DWbKyzuiQzVHo3Bxgwm9AdXVRZJQFF9JHC/jvcbp4lxCC+IY=
  app:
    master: moscowdjango
    dev: moscowdjango-staging
  run:
    - "python manage.py migrate --noinput"
    - "python manage.py collectstatic --noinput"
